### PR TITLE
Add Documentation

### PR DESCRIPTION
**Pull request by whytro**
I've added some documentation for `py_osrm`, using Sphinx, so it can be hosted on readthedocs.io. It will require subscribing the project on the readthedocs dashboard after the files are added, though it might require a few more additional file tinkering afterwards to get it working.

I have a test version up here, if you would like to see how it looks and add feedback:
https://whytro-test.readthedocs.io/en/latest/

Some additions that need to be made here are:
 - osrm-datastore/shared memory usage

### CODE REVIEW

**Review by nilsnolde — COMMENTED** [review]
I’d strongly prefer markdown tbh. I used to do Sphinx as well, but that’s really terrible syntax and I always loathed it. Since a while mkdocs is the better way to go IMO. There’s all kinds of well maintained extensions for it, and we can easily host it on GitHub Actions. 

An example (without docstrings) is eg https://github.com/valhalla/valhalla/tree/master/docs. That theme is awesome for UX, eg searching for stuff is sooo much better. 

WDYT @SiarheiFedartsou @whytro ?

**Comment by nilsnolde** [comment]
FWIW, I’d also try to put the API documentation in-code, ie as python docstrings. That way it’ll show up in the hosted docs and in IDEs. I didn’t use mkdocs for that yet, but I’m sure it’s an easy setup so it auto-extracts the docstrings and constructs the docs from it.

**Comment by whytro** [comment]
I can work with either. Most of the time spent in documentation writing was looking back at the code and checking syntax/checking references, rather than formatting, so a conversion from Sphinx to Markdown shouldn't take too long. 

I'll go ahead and look into Mkdocs & Github Pages, so we can switch to that if preferred.

**Comment by nilsnolde** [comment]
Ok thanks:)

Github actions is lacking a bit of docs around publishing it. Easiest is to use „mkdocs gh-deploy —strict“ command (or so, on mobile right now) locally, that’ll create a branch „gh-pages“ which you can push to remote. Then in GH UI Settings we just need to point it there. And add a small workflow like this one: https://github.com/valhalla/valhalla/blob/master/.github/workflows/gh-pages.yml

**Comment by whytro** [comment]
I'm testing out autogenerated documentation from docstrings now, since I've gone back and added docstrings to the relevant bindings code. I've mainly used [PEP 257](https://peps.python.org/pep-0257/) convention for now.

**Comment by nilsnolde** [comment]
Sounds good thanks @whytro ! Doesn’t have to look perfect either. Focus rather on maintainability/less complexity than UI.

**Comment by whytro** [comment]
I'll be closing this to create another PR for the Mkdocs documentation route!

**Pull request closed without merging**
